# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, World!
  displayName: 'Run a one line script'

- script: |
    npm install
    npm test
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yam1
  displayName: 'npm install and build'
